modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="platinumvisuals"
version="1.5.1"
displayName="Platinum Visuals"
authors="Matun"
description='''Client visuals and HUD. Right Ctrl opens the menu. V toggles Anti Invis.'''
[[mixins]]
config="platinumvisuals.mixins.json"
[[dependencies.platinumvisuals]]
modId="neoforge"
type="required"
versionRange="[21.11.45,21.12)"
ordering="NONE"
side="CLIENT"
[[dependencies.platinumvisuals]]
modId="minecraft"
type="required"
versionRange="[1.21.11]"
ordering="NONE"
side="CLIENT"
